apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: flask
  namespace: fleet-local
spec:
  repo: https://github.com/aws-samples/rancher-on-aws-workshop
  branch: main
  targetNamespace: flask
  paths:
    - /static/fleet/flask-demo-app