apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: flask
  namespace: fleet-local
spec:
  repo: https://github.com/aws-samples/rancher-on-aws-workshop
  branch: main
  targetNamespace: flask
  paths:
    - /static/fleet/flask-demo-app
---
apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: flask
spec:
  label: Flask
  target: _blank
  description: Flask Demo Application
  group: Flask Demo App
  label: Flask Demo App
  sideLabel: Flask
  toService:
    name: flask
    namespace: flask
    port: "5000"
    path: /
    scheme: http