apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rancher-demo-app
  namespace: fleet-local
spec:
  repo: https://github.com/aws-samples/rancher-on-aws-workshop
  branch: main
  targetNamespace: default
  paths:
    - /static/fleet/rancher-demo-app
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: flask-demo-app
  namespace: fleet-local
spec:
  repo: https://github.com/aws-samples/rancher-on-aws-workshop
  branch: main
  targetNamespace: default
  paths:
    - /static/fleet/flask-demo-app